module.exports = {
    JSONP: 'jsonp',
    JSON: 'json',
    JSONP_CALLBACK: 'jsonpCallback',
    DATA_TYPE: 'dataType',
    POST: 'post',
    GET: 'get',
    TIME_OUT: '30s',
    MAX_LENGTH: 200,
    EXPIRE_TIME: 7200000,
    TITLE: '',
    KEYWORDS: '',
    DESCRIPTION: '',
    SIZE: 'b',
    SCRIPT_CACHE_KEY: 'script_code',
    DUBBO_ERROR: 'Dubbo service error: ',
    DUBBO_MESSAGE: 'dubbo service message',
    DUBBO_INIT: 'dubbo init message',
    DUBBO_READY: 'dubbo ready message'
};
