module.exports = {
    JSONP: 'jsonp',
    JSON: 'json',
    JSONP_CALLBACK: 'jsonpCallback',
    DATA_TYPE: 'dataType',
    POST: 'post',
    GET: 'get',
    TIME_OUT: '30s',
    LOGIN_API: 'member/usernameCall',
    COOKIE_KEY: 'wtoipSessionId',
    DOMAIN: 'wtoip.com',
    FRIENDS_KEY: 'www.wtoip.com',
    MAX_LENGTH: 200,
    EXPIRE_TIME: 7200000,
    TITLE: '',
    KEYWORDS: '',
    DESCRIPTION: '',
    SIZE: 'b',
    SCRIPT_CACHE_KEY: 'script_code',
    DUBBO_ERROR: 'Dubbo service error: ',
    DUBBO_MESSAGE: 'dubbo service message'
};
